---
id: mysql-and-postgresql-and-japanese-full-text-search
base_name: mroonga-and-pgroonga
tags:
- rabbit
- mysql
- postgresql
- full-text-search
- mroonga
- pgroonga
presentation_date: 2016-02-09
version: 2016.2.9.1
licenses:
- CC BY 3.0
- CC BY-SA 4.0
slideshare_id: mysql-and-postgresql-and-japanese-full-text-search
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
